baseURL = "/"
languageCode = "en-us"
title = "Rebar3"
theme = "docsy"

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[params]
copyright = "Tristan Sloughter"
offlineSearch = true
# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/tsloughter/rebar3.org"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/erlang/rebar3"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "https://lists.basho.com/mailman/listinfo/rebar_lists.basho.com"
	icon = "fa fa-envelope"
    desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/search?q=rebar3"
	icon = "fab fa-twitter"
    desc = "Discuss us on Twitter"
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/erlang/rebar3"
	icon = "fab fa-github"
    desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://erlanger.slack.com/archives/C0SEMDD36"
	icon = "fab fa-slack"
    desc = "Chat with other project developers"
